---
- name: Download cephadm
  shell: "curl --silent --remote-name --location https://download.ceph.com/rpm-reef/el9/noarch/cephadm"

- name: Make cephadm executable
  shell: "sudo chmod +x cephadm"

- name: Add repository
  shell: "./cephadm add-repo --release reef"

- name: Install ceph-common
  shell: "sudo ./cephadm install ceph-common"


