---
- name: Descargar cephadm
  shell: "curl --silent --remote-name --location {{ cephadm_download_url }}"

- name: Hacer cephadm ejecutable
  shell: "chmod +x cephadm"

- name: Añadir repositorio
  shell: "./cephadm add-repo --release {{ ceph_release }}"

- name: Instalar ceph-common
  shell: "sudo ./cephadm install ceph-common"
