---
- name: Instalar y configurar el clúster de Ceph
  hosts: ceph
  become: yes
  roles:
    - chrony
    - docker
    - ceph

 - name: Bootstrap Ceph cluster
   hosts: ceph_main  # Utilizando el host adecuado para esta tarea
   tasks:
     - name: Ejecutar el comando cephadm bootstrap
       become: yes
       command: >
         sudo ./cephadm bootstrap 
         --mon-ip {{ hostvars[groups['ceph_main'][0]].ansible_host }} 
         --initial-dashboard-user {{ ceph_initial_dashboard_user }} 
         --initial-dashboard-password {{ ceph_initial_dashboard_password }} 
         --dashboard-password-noupdate 
         --cluster-network={{ ceph_cluster_network }} 
         --allow-fqdn-hostname

- name: Copiar clave SSH a nodos ceph
  hosts: ceph_main
  become: yes
  tasks:
    - name: Leer el contenido de ceph.pub
      slurp:
        src: /etc/ceph/ceph.pub
      register: ceph_pub_content

- name: Agregar clave SSH a nodos ceph
  hosts: ceph
  become: yes
  tasks:
    - name: Asegurarse de que existe el directorio .ssh
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Agregar la clave ceph.pub a authorized_keys
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ hostvars[groups['ceph_main'][0]]['ceph_pub_content']['content'] | b64decode }}"
        create: yes
        owner: root
        group: root
        mode: '0600'

- name: Agregar hosts y aplicar configuración Ceph
  hosts: ceph_main
  become: yes
  tasks:
    - name: Agregar hosts al clúster Ceph
      shell: |
        {% for host in groups['ceph'] %}
        sudo ceph orch host add {{ host }} {{ hostvars[host].ansible_host }}
        {% endfor %}

    - name: Aplicar colocación de MON
      shell: |
        sudo ceph orch apply mon --placement="{{ groups['mon'] | join(',') }}"

    - name: Aplicar colocación de MGR
      shell: |
        sudo ceph orch apply mgr --placement="{{ groups['mgr'] | join(',') }}"

    - name: Etiquetar nodos OSD
      shell: |
        sudo ceph orch host label add {{ item }} osd-node
      loop: "{{ groups['osd'] }}"

    - name: Etiquetar nodos MON
      shell: |
        sudo ceph orch host label add {{ item }} mon
      loop: "{{ groups['mon'] }}"

    - name: Etiquetar nodos MGR
      shell: |
        sudo ceph orch host label add {{ item }} mgr
      loop: "{{ groups['mgr'] }}"

    - name: Aplicar configuración de OSD
      shell: |
        sudo ceph orch apply osd --all-available-devices
